# Site
repository: changjun6518/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 최창준
title: Java Backend Devoloper
email: aowert6518@gmail.com
# email_title: Email (Email title override)
phone: 010-4008-5891
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
github_username:  changjun6518
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# # Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
# about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  <mark>Spring Boot</mark> <mark>MariaDB</mark> <mark>JPA</mark> <mark>Git</mark> 을 사용하여 웹 어플리케이션을 개발하고 배포한 경험이 있습니다. <br>
  <mark>객체지향프로그래밍</mark> <mark>클린코드</mark> <mark>TDD</mark> 에 대해 필요성을 느끼고 학습한 경험이 있습니다.
content:
  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Language
        description: | # this will include new lines to allow paragraphs
          - Java
      - layout: left
        title: Framworks
        description: |
          - Spring Boot, Spring MVC
      - layout: left
        title: Databases / ORM
        description: |
          - MariaDB, JPA
      - layout: left
        title: DevOps
        description: |
          - Git
  - title: Project
    layout: list
    content:
      - layout: left
        title: 홍익대학교 딥러닝 연구실 PEM
        sub_title: 데이터 관련 API 개발 및 배포
        caption: 2021.07 ~ 2022.02
        quote: >
          raw data를 parsing하고 데이터베이스에 저장하고 저장된 데이터를 연구원들에게 제공하기 위해 관련 API를 개발하고 배포하였습니다.
        description: | # this will include new lines to allow paragraphs
          - raw data를 JPA를 통해 데이터베이스에 저장
            - <b>Insert시 많은 시간 소요 문제 해결함</b> (save(), saveAll(), bulk Insert)
          - spring boot로 서버 구축 및 CRUD API 개발
          - Azure 가상머신과 Jenkins, Github를 통해 CI/CD 환경 구축 및 배포 
  - title: Education
    layout: list
    content:
      - layout: left
        title: 홍익대학교
        sub_title: 도시공학과, 컴퓨터공학과
        caption: 2015.03 ~ 2022.02
#         quote: >
#           Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          <b>자료구조, 알고리즘, 운영체제, 데이터베이스, 네트워크</b> 등 computer science 에 대해 학습하였습니다.
  - title: Temp
    layout: text
    content:
      - layout: list
        title: 도전
        description: |
          안녕하세요
#   - title: Self-introduction
#     layout: list
#     content:
#       - layout: left
#         title: 도전과 성장
#         description: |
#         <u>새로운 지식과 기술을 습득할때 뿌듯함을 느낍니다.</u>
#         처음에는 어렵고 이해하기 어렵지만 계속해서 반복적으로 학습하고 사용해보며 익숙해질때 성장하고 있음을 느낍니다.
#         매일 성장하는 것을 목표로 개발하고 학습하고 있습니다. 
#         <u>책을 통한 지식 습득이나 프로젝트를 진행하며 기술을 적용해보며 학습하고 있습니다.</u>
# #       - layout: left
#         title: 유지보수와 협업에 좋은 코드
#         description: |
#         프로젝트를 진행하며 유지보수와 협업의 필요성을 느끼고 그에 따른 좋은 코드는 무엇인지 고민해보았습니다.
#         이에 대한 키워드로 <u>객체지향 프로그래밍과 클린코드와 TDD</u> 등 을 알게 되었고 스터디를 진행하며 학습하였습니다.
#         <u>미션 기반 작은 토이 프로젝트를 진행하면서 해당 지식들을 적용해보며 몸소 느껴볼 수 있었습니다.</u>
#       - layout: left
#         title: 소프트 스킬
#         description: |
#         여러 스터디를 운영하면서 의사소통의 중요성을 알게되었습니다. 
#         <u>스터디 장으로서 의견을 물어보고 조율하는 경험은 수동적이였던 저에게 큰 도움이 되었습니다.</u>
#         이 경험을 통해 적극적인 의사소통의 중요성을 알게되었고 노력하고 있습니다.
#         <u>페어프로그래밍</u>을 진행하면서 혼자하는 코딩보다 같이하는 코딩이 주는 장점을 느낄 수 있었습니다.
#         <u>특히 내가 하지 못했던 생각을 알게되고 같이 토론하며 생각을 정리할때 큰 도움이 되었습니다.</u>
#         나아가 IDE 개발 단축키 등 소소한 팁을 서로 공유할때 큰 보람을 느꼈습니다.
#       - layout: left
#         title: 적극성과 문제해결능력
#         description: |
#         학부연구생으로 근무하며 당시 연구실에 있었던 문제를 파악하고 교수님께 제안드려 해결한 경험이 있습니다.
#         연구원들이 사용하는 데이터가 NAS에 저장되어 있었고 데이터에 대한 인수인계가 적절히 이뤄지지 않고 있었습니다. 
#         데이터를 디비에 저장하고 연구원들이 사용할 수 있도록 하고 인수인계를 위해 메뉴얼을 작성하였습니다.
#         <u>자발적으로 나서서 이러한 문제를 해결하였고 연구실에 큰 가치를 기여했다고 생각합니다.
#         문제를 해결하는데 있어서 현재 상황에서 어떤 선택을 하는 것이 적합한지 고민하고 적용해보았습니다.</u>
        
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
